### ISSUE TITLE
Review #1

### ISSUE THREAD

**Issue by Kayphaz** [douglaspujol/slotmachineslot#1]
Boa tarde Douglas,
A gente espera como resultado do teste o projeto do cocos para que consigamos executar o mesmo aqui e analisar as mudanças efetuadas no mesmo.

Quanto a matriz que tu gerou nessa JS, acho que tu não entendeu o que é pra fazer.
Da uma olhada nesse jogo https://games.netent.com/video-slots/ozzy-osbourne/ pra ter uma ideia como é um jogo de slot.
A gente quer q tu implemente o resultado aleatorio no jogo que a gente proveu.
Caso não consiga terminar o mesmo, queremos ver o quanto tu conseguiu avançar.
Se tiver alguma duvida, pode perguntar aqui.

**Comment by douglaspujol** [comment]
Boa tarde pessoal!
Eu não consegui finalizar o projeto. Me dediquei essa semana em estudar a plataforma CocosCreator e também busquei aprender TypeScript.
Eu consegui entender cada método do projeto mas acabei tendo muita dificuldade na hora de implementar os requisitos. Eu estou com muita curiosidade para ver a resolução das propostas. 
Eu sei que não possuo todas as competências técnicas para trabalhar com vocês, mas a vontade de aprender é muito grande. A habilidade técnica vem com o tempo de trabalho. Mas a fome por aprender e trabalhar com a equipe é uma coisa que já precisa existir em cada colega de trabalho. Isso eu tenho! 
 
https://github.com/douglaspujol/slotdesafio

Agradeço a oportunidade de participar do desafio. Acabei demorando mais para postar pois precisei aprender muita coisa nova. Foi muito Proveitoso para mim. Se precisarem de mim, podem me chamar! 

Grande abraço

**Comment by Kayphaz** [comment]
Boa tarde Douglas, desculpe a demora.
Vou te passar o repo de um de nossos funcionarios com a resolução
https://github.com/FlavioFS/slot-test-client
